server:
  port: 9090
  servlet:
    context-path: /api/v1/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: firoze28
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  default-produces-media-type: application/json

